// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxbrLz6AZzq6SRse3ZKFD4hMxejQ1FOYM',
    appId: '1:431101350822:android:173836e44899fc2d783567',
    messagingSenderId: '431101350822',
    projectId: 'ecomprofire',
    storageBucket: 'ecomprofire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSzGwsr6TSWPT6nkU5_Cek6N2n5ZfT17M',
    appId: '1:431101350822:ios:c58abf0758133384783567',
    messagingSenderId: '431101350822',
    projectId: 'ecomprofire',
    storageBucket: 'ecomprofire.appspot.com',
    androidClientId: '431101350822-6k3sjok29bo98n1mur7ot27n4v11gafu.apps.googleusercontent.com',
    iosClientId: '431101350822-amj0nedqq105g8s5cj9kc1j528q5l2if.apps.googleusercontent.com',
    iosBundleId: 'site.tunckankilic.tuncforworkalt',
  );
}
